# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 14:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_page', models.URLField()),
                ('developer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('source_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('game_logo', models.ImageField(null=True, upload_to='')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Category')),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Score',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Game_State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(to='community.Game')),
                ('player_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game_state',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Player'),
        ),
        migrations.AddField(
            model_name='game_score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Player'),
        ),
    ]
