# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_auto_20170126_1436'),
        ('community', '0002_auto_20170126_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Game_Category',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='developer_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='games',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_id',
        ),
        migrations.AlterField(
            model_name='game',
            name='developer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Developer'),
        ),
        migrations.AlterField(
            model_name='game_score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player'),
        ),
        migrations.AlterField(
            model_name='game_state',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player'),
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
