# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20170120_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
