# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='corp_page',
            field=models.URLField(blank=True),
        ),
    ]
