# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:17
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.management import create_permissions


def migrate_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial')
    ]

    operations = [
        migrations.RunPython(migrate_permissions)
    ]
