# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 20:07
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def add_group_permissions(apps, schema_editor):

    # Developer
    group, created = Group.objects.get_or_create(name='developer')
    if created:
        group.permissions.add(
            Permission.objects.get(codename='add_game'),
            Permission.objects.get(codename='change_game'),
            Permission.objects.get(codename='delete_game')
        )

    # Player
    group, created = Group.objects.get_or_create(name='player')
    if created:
        group.permissions.add(
            Permission.objects.get(codename='play_game'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
