# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 14:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_auto_20170120_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('gift_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Game')),
                ('gift_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webshop.Gift')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('result', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Transaction'),
        ),
    ]
