# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='gift_id',
            new_name='gift',
        ),
        migrations.AlterField(
            model_name='gift',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
