# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_auto_20170126_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player'),
        ),
    ]
