# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_auto_20170214_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.0)]),
            preserve_default=False,
        ),
    ]
