# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_auto_20170216_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='pid',
            new_name='transaction',
        ),
    ]
